### ISSUE TITLE
Tab switch does nothing while part of the page is highlighted 

### ISSUE THREAD

**Issue by zcskywire2** [markasoftware/SpecDB#26] opened 2017-07-29 06:17 UTC
Found this by accident. Basically just can't switch between compare and select when you highlight any part of the page. The ui animation plays showing that it received the click event but nothing else happens.

**Comment by markasoftware** [comment] 2017-07-29 14:44
Weird, I can't reproduce this issue. Could you provide details on what OS and browser you're using? It works fine for me on Arch Linux with Firefox, Chromium, and Opera (which is basically Chromium)

**Comment by markasoftware** [comment] 2017-07-29 14:53
I can also confirm that it still works in Chromium's mobile "emulator" mode, although it's still a long shot from a real mobile device and I'm still waiting for Browserstack to approve my access to the open-source plan.

**Comment by zcskywire2** [comment] 2017-07-29 15:17
I have received this issue on chome for Android and chrome for Windows 10.

**Comment by zcskywire2** [comment] 2017-07-29 15:19
So okay, its only the portion where the arrow is drawn on the tab switch button that does not function properly

**Comment by markasoftware** [comment] 2017-07-29 16:17
Ok, I can confirm that clicking the arrow while text is selected in chromium-based browses does not work. However, it does work in Firefox, so I'm inclined to believe this may actually be a browser issue. I've created a minimal reproducible example in this codepen: https://codepen.io/markasoftware/pen/QMyEow. Let me know if this issue also occurs in Edge.

I could possibly workaround this issue by embedding the image using an `<svg>` tag instead of `<img>`.

**Comment by zcskywire2** [comment] 2017-07-29 16:27
Just tested edge ( no I will not set it as my main browser windows stop nagging) works fine on edge. Must be a issue with chromium based browsers then.

**Comment by markasoftware** [comment] 2017-07-31 18:25
Since this is a browser bug, and one that is not likely to affect/be noticed by anybody, I'm going to close this issue.

**Closed by markasoftware** 2017-07-31 18:25 UTC
Labels: bug
